input {
  file {
    path => "/usr/share/logstash/ingest_data/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
  }
}

filter {
  grok {
    match => { "message" => "%{IPORHOST:client_ip} - - \[%{HTTPDATE:timestamp}\] \"%{WORD:http_method} %{DATA:url} HTTP/%{NUMBER:http_version}\" %{NUMBER:response_code} %{NUMBER:body_sent_bytes} \"%{DATA:referrer}\" \"%{DATA:user_agent}\"" }
  }
  
  date {
    match => [ "timestamp", "dd/MMM/yyyy:HH:mm:ss +0000" ]
    # timezone => "Europe/Istanbul"
    target => "@timestamp"
  }

  mutate {
    convert => {
      "response_code" => "integer"
      "body_sent_bytes" => "integer"
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "web-server-logs"
  }
 
  stdout { codec => rubydebug }
}
